#!/usr/bin/env bash
netstat -a -p

#The command is used to display the listening ports
# -a: Displays all listening and non-listening sockets
# -p: Shows the program or process associated with the socket.

